### ISSUE TITLE
hooks in nested directories are not called.

### ISSUE THREAD

**Issue by eoussama** [YSI-Coding/y_hooks#1]
This is quite a strange one.
The only hook that's called is one found in the first (_alphabetically ordered_) file from a given directory.
Take this as an example:

```pawn
#include "./core/entities/item/food/banana"
#include "./core/entities/item/food/burger"
#include "./core/entities/item/food/apple"

// Drinks
#include "./core/entities/item/drinks/water_bottle"
#include "./core/entities/item/drinks/orange_juice"

// Clothes
#include "./core/entities/clothes/item/skin"
#include "./core/entities/clothes/item/hat"
```

All of the above files have an `OnItemUsed` hook, but only the ones in `banana.inc`, `orange_juice.inc`, and `hat.inc` are called.
Only after putting all of those files in the same directory as the file they are being included in seems to solves this.

**Comment by Y-Less** [comment]
That's not a hooks issue.  Nothing in those files will work because you've included them wrong.
